In [1]:
from PIL import Image
import numpy as np
import ICA
import matplotlib.pyplot as plt
import math

data1 = np.array(Image.open("data/image1.png").convert('L'))
data2 = np.array(Image.open("data/image2.png").convert('L'))
height = data1.shape[0]
width = data2.shape[1]

In [2]:
data1

array([[179, 179, 179, ..., 133, 113, 104],
       [179, 179, 179, ..., 129, 121,  97],
       [179, 179, 179, ..., 130, 117, 106],
       ...,
       [ 60,  60,  60, ..., 145, 146, 144],
       [ 60,  60,  62, ..., 142, 142, 142],
       [ 17,  60,  62, ..., 142, 142, 142]], dtype=uint8)

In [3]:
data2

array([[173, 173, 173, ..., 146, 127, 113],
       [173, 173, 173, ..., 142, 133, 106],
       [173, 173, 173, ..., 142, 130, 113],
       ...,
       [ 54,  54,  56, ..., 131, 130, 129],
       [ 54,  54,  60, ..., 130, 130, 132],
       [ 26,  54,  60, ..., 130, 130, 132]], dtype=uint8)

In [4]:
data1 = data1.flatten()
data1

array([179, 179, 179, ..., 142, 142, 142], dtype=uint8)

In [5]:
data2 = data2.flatten()
data2

array([173, 173, 173, ..., 130, 130, 132], dtype=uint8)

In [6]:
data = np.asmatrix(np.dstack([data1, data2]))
data

matrix([[179, 173],
        [179, 173],
        [179, 173],
        ...,
        [142, 130],
        [142, 130],
        [142, 132]], dtype=uint8)

In [7]:
w = np.array([[4 / 5, 3 / 5], [1 / math.sqrt(2), 1 / math.sqrt(2)]])
ans = ICA.answer(w, data, 2)
a0, a1 = np.split(ans, 2 ,1)

In [8]:
a0

matrix([[3.95761974],
        [3.95761974],
        [3.95761974],
        ...,
        [3.47408141],
        [3.47408141],
        [3.38167621]])

In [9]:
a1

matrix([[3.11948214],
        [3.11948214],
        [3.11948214],
        ...,
        [2.00666985],
        [2.00666985],
        [2.13594849]])

In [10]:
a0 = a0.reshape(height, width)
a0

matrix([[ 3.95761974,  3.95761974,  3.95761974, ...,  2.13396816,
          1.67654722,  1.72251196],
        [ 3.95761974,  3.95761974,  3.95761974, ...,  2.05172449,
          1.93343975,  1.57858555],
        [ 3.95761974,  3.95761974,  3.95761974, ...,  2.11848801,
          1.80499348,  1.856039  ],
        ...,
        [ 1.51087062,  1.51087062,  1.41846542, ...,  3.62816936,
          3.74113548,  3.65381104],
        [ 1.51087062,  1.51087062,  1.36718205, ...,  3.47408141,
          3.47408141,  3.38167621],
        [-0.06628781,  1.51087062,  1.36718205, ...,  3.47408141,
          3.47408141,  3.38167621]])

In [11]:
a1 = a1.reshape(height, width)
a1

matrix([[3.11948214, 3.11948214, 3.11948214, ..., 3.4463073 , 3.11906751,
         2.6195253 ],
        [3.11948214, 3.11948214, 3.11948214, ..., 3.36793148, 3.14654051,
         2.48236761],
        [3.11948214, 3.11948214, 3.11948214, ..., 3.32288611, 3.13280401,
         2.52943456],
        ...,
        [0.78780141, 0.78780141, 0.91708005, ..., 1.93617307, 1.82648838,
         1.85193979],
        [0.78780141, 0.78780141, 1.08554661, ..., 2.00666985, 2.00666985,
         2.13594849],
        [0.91485115, 0.78780141, 1.08554661, ..., 2.00666985, 2.00666985,
         2.13594849]])

In [12]:
a0 = np.where(a0 < 0, 0, a0)
a1 = np.where(a1 < 0, 0, a1)

In [13]:
a0

array([[3.95761974, 3.95761974, 3.95761974, ..., 2.13396816, 1.67654722,
        1.72251196],
       [3.95761974, 3.95761974, 3.95761974, ..., 2.05172449, 1.93343975,
        1.57858555],
       [3.95761974, 3.95761974, 3.95761974, ..., 2.11848801, 1.80499348,
        1.856039  ],
       ...,
       [1.51087062, 1.51087062, 1.41846542, ..., 3.62816936, 3.74113548,
        3.65381104],
       [1.51087062, 1.51087062, 1.36718205, ..., 3.47408141, 3.47408141,
        3.38167621],
       [0.        , 1.51087062, 1.36718205, ..., 3.47408141, 3.47408141,
        3.38167621]])

In [14]:
a1

array([[3.11948214, 3.11948214, 3.11948214, ..., 3.4463073 , 3.11906751,
        2.6195253 ],
       [3.11948214, 3.11948214, 3.11948214, ..., 3.36793148, 3.14654051,
        2.48236761],
       [3.11948214, 3.11948214, 3.11948214, ..., 3.32288611, 3.13280401,
        2.52943456],
       ...,
       [0.78780141, 0.78780141, 0.91708005, ..., 1.93617307, 1.82648838,
        1.85193979],
       [0.78780141, 0.78780141, 1.08554661, ..., 2.00666985, 2.00666985,
        2.13594849],
       [0.91485115, 0.78780141, 1.08554661, ..., 2.00666985, 2.00666985,
        2.13594849]])

In [15]:
a0 = (50 * a0).astype(np.uint8)
a1 = (50 * a1).astype(np.uint8)

In [16]:
a0

array([[197, 197, 197, ..., 106,  83,  86],
       [197, 197, 197, ..., 102,  96,  78],
       [197, 197, 197, ..., 105,  90,  92],
       ...,
       [ 75,  75,  70, ..., 181, 187, 182],
       [ 75,  75,  68, ..., 173, 173, 169],
       [  0,  75,  68, ..., 173, 173, 169]], dtype=uint8)

In [17]:
a1

array([[155, 155, 155, ..., 172, 155, 130],
       [155, 155, 155, ..., 168, 157, 124],
       [155, 155, 155, ..., 166, 156, 126],
       ...,
       [ 39,  39,  45, ...,  96,  91,  92],
       [ 39,  39,  54, ..., 100, 100, 106],
       [ 45,  39,  54, ..., 100, 100, 106]], dtype=uint8)

In [18]:
answer1 = Image.fromarray(np.asarray(a0))
answer2 = Image.fromarray(np.asarray(a1))

answer1.save("answer3.png")
answer2.save("answer4.png")